FORMAT: 1A
HOST: wtf.com

# puzzle-dashboard

Blah blah blah api blah blah

## i18n

All values must be in USD. If required values in another currency, we must add `currency` header to request. Same shit with language options.

## Portfolio summary [/portfolio/summary]

### Get portfolio summary [GET]

+ Response 200 (application/json)
        {
            netAssetValue: {
                value: 8097386,
                change: 5.02
            },
            changes: {
                oneWeek: -31.83,
                oneMonth: 219.83,
                threeMonths: 394958.83
            },
            caquisitionCost: 1291450,
            profitLoss: 6805936
        }

## Portfolio table [/portfolio/table]

### Get portfolio table [GET]

+ Response 200 (application/json)
        [
            {
                asset: 'Bitcoin',
                symbol: 'BTC',
                qty: '10.0049495',
                price: {
                    value: 13383.30,
                    change: -13.76
                },
                exposure: 140394,
                profitLoss: {
                    value: 13949494,
                    change: 23.44
                },
                weight: 4.44
            },
            {
                asset: 'Ethereum',
                symbol: 'ETH',
                qty: 140.949584,
                price: {
                    value: 1506.90,
                    change: 13.76
                },
                exposure: 90049,
                profitLoss: {
                    value: 999576,
                    change: 35.92
                },
                weight: 6.52
            },
            {
                asset: 'Litecoin',
                symbol: 'LTC',
                qty: 2058.48,
                price: {
                    value: 150.39,
                    change: -13.76
                },
                exposure: 24,994,
                profitLoss: {
                    value: 2483,
                    change: -10.11
                },
                weight: 2.94
            },
            {...}
        ]

## Portfolio Chart [/portfolio/chart/value?period={period}]

### Get chart data [GET]

+ Parameters
    + period (string)
        Must be one of these strings 1d, 1w, 1m, 3m, 1y, all. If param not specified return all

+ Response 200 (application/json)
        [
            {
                timestamp: 1517691315,
                value: 100000
            },
            {
                timestamp: 1517691399,
                value: 100100
            },
            {...}
        ]

## Manage asset's single transaction [/assets/tx{?asset}]

### Get all txs [GET]

+ Parameters
    + asset (string, required)
        btc, eth, ltc, etc...

+ Response 200 (application/json)
        {
            asset: 'Bitcoin',
            symbol: 'BTC',
            txs: [
                {
                    id: '0x00000',
                    type: 'sell',
                    timestamp: 1517691315,
                    exchange: 'Bittrex',
                    value: '1.517691315',
                    price: 10495.45
                },
                {
                    id: '0x00001',
                    type: 'buy',
                    timestamp: 1517691457,
                    exchange: 'Poloniex',
                    value: '2.347586',
                    price: 10250.50
                },
                {...}
            ]
        }

### Add tx [POST]

+ Request (application/json)
        {
            type: 'sell',
            asset: '0x00',
            value: '1000.1384859373',
            price: '10000',
            timestamp: 1517691457,
            exchange: '0x001'
        }

+ Response (application/json)
        {
            id: '0x00000',
            type: 'sell',
            asset: 'btc',
            timestamp: 1517691457,
            exchange: 'Bittrex',
            value: '1000.1384859373',
            price: 10000
        }

### Del tx [DELETE]

+ Parameters
    + txId (string, required)
        Unique tx uuid or txhash

+ Response 200 (application/json)
        {
            id: '0x00001'
        }

## Exchanges [/exchanges]

### Get list of available exchanges [GET]

+ Response 200 (application/json)
    [
        {
            id: '0x00000',
            title: 'Bittrex'
        }.
        {
            id: '0x00001',
            title: 'Poloniex'
        }
    ]

## Assets [/assets]

### Get list of available assets [GET]

+ Response 200 (application/json)
    [
        {
            id: '0x00',
            name: 'Bitcoin',
            symbol: 'BTC'
        },
        {
            id: '0x01',
            name: 'Ethereum',
            symbol: 'ETH'
        },
        {...}
    ]
