version: '2'
services:
  portfolio:
    image: jincort/backend-portfolio:develop
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 3000:3000
      - 443:4000
    volumes:
      - ./:/usr/src/app
    links:
      - redis
    depends_on:
      - mongo
    tty: true
    networks:
      default:
        ipv4_address: 10.100.0.2

  redis:
    image: jincort/backend-redis:production
    ports:
      - "6379"
    volumes:
      - ./storage/redis:/data
    networks:
      default:
        ipv4_address: 10.100.0.4

  mongo:
    image: jincort/backend-mongodb:production
    volumes:
        - ./storage/mongodb:/data/db
    networks:
      default:
        ipv4_address: 10.100.0.7
    ports:
      - 27017:27017
      - 28017:28017

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1
