version: '2'
services:
  portfolio:
    image: registry.jincor.com/backend/ico:latest
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 80:3000
      - 443:4000
    links:
      - rpc
    depends_on:
      - rpc
    volumes:
      - /root/ethereum-blockchain:/home/ethereum
    restart: always
