version: '2'
services:
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 80:3000
      - 443:4000
    links:
      - auth
      - redis
      - verify
    depends_on:
      - mongo
    restart: always
    networks:
      default:
        ipv4_address: 10.100.0.2

  redis:
    image: registry.jincor.com/backend/redis:latest
    ports:
      - "6379"
    volumes:
      - ./storage/redis:/data
    networks:
      default:
        ipv4_address: 10.100.0.4

  mongo:
    image: registry.jincor.com/backend/mongodb:latest
    volumes:
        - ./storage/mongodb:/data/db
    networks:
      default:
        ipv4_address: 10.100.0.7
    ports:
      - "27017"
      - "28017"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1
